name: Rust Project Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build project
        run: |
          cargo install trunk
          rustup target add wasm32-unknown-unknown
          trunk build --release

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "."
          api_location: ""
          output_location: "dist"


